[cluster]
host = "host_or_ip_of_couchbase_cluster"  # host.docker.internal if on localhost
username = "couchbase_username"
password = "couchbase_password"
bucket = "bucket_name"
# Whether the bucket should be flushed at the start
flush_bucket = true

[transactions]
# Could also be "persist_to_majority" or "majority_and_persist" or "none" (though latter is not supported)
# If on a single-node cluster make sure buckets have 0 replicas configured
durability = "majority"
verbose_logging = true
# How many transactions to run
iterations = 10000

[transfer]
# How much to transfer between the two users
amount = 50

[open_telemetry]
zipkin_endpoint = "http://host.docker.internal:9411/api/v2/spans"

[prometheus]
port = 9000